---
kind: pipeline
name: Build and Test

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test
    environment:
      SECRET_KEY:
        from_secret: SECRET_KEY
trigger:
  event:
    - push

---
kind: pipeline
name: e2e tests
steps:
  - name: Test
    image: node:10
    commands:
      - yarn install
      - yarn lerna run prepack
      - cd packages/node
      - npm link
      - cd e2e
      - yarn install
      - npm link @bearer/node
      - yarn test
    environment:
      SECRET_KEY:
        from_secret: SECRET_KEY
trigger:
  event:
    - push

---
kind: pipeline
name: Release (next)

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: release
    image: node:10
    commands:
      - git checkout  -b master
      - yarn lerna-publish --dist-tag=next --yes

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-next-*

---
kind: pipeline
name: Release (forced)

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test

  - name: release (force)
    image: node:10
    commands:
      - yarn lerna-publish --force-publish --dist-tag=latest

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-latest-*
---
kind: pipeline
name: Canary release

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test
trigger:
  event:
    - push
  branch:
    - canary
---
kind: signature
hmac: 9bfc808669b407ac0a54d33bcc6c0f637396006b0895834251e0c769b3e34290

...
