---
kind: pipeline
name: Build and Test

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test
trigger:
  event:
    - push

---
kind: pipeline
name: Release (next)

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: release
    image: node:10
    commands:
      - git checkout master
      - yarn lerna-publish --dist-tag=next --yes

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-next-*

---
kind: pipeline
name: Release (forced)

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test

  - name: release (force)
    image: node:10
    commands:
      - yarn lerna-publish --force-publish --dist-tag=latest

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-latest-*
---
kind: pipeline
name: Canary release

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test
trigger:
  event:
    - push
  branch:
    - canary
---
kind: signature
hmac: 19c57583c7ce289b8c7beba2bea6ae3b3aeef9aaa7b96a008c8e1ebf98ef1e1b

...
