---
kind: pipeline
name: Build and Test

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test
    environment:
      SECRET_KEY:
        from_secret: SECRET_KEY
trigger:
  event:
    - push

---
kind: pipeline
name: Publish package
steps:
  - name: Install
    image: node:10
    commands:
      - yarn install
  - name: Publish
    image: node:10
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - git fetch origin master
      - git checkout master
      - git remote set-url origin https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/Bearer/bearer-js.git
      - yarn lerna publish --dist-tag=test --conventional-commits --create-release=github --yes
    environment:
      SECRET_KEY:
        from_secret: SECRET_KEY
      NPM_TOKEN:
        from_secret: NPM_TOKEN
      GITHUB_USERNAME:
        from_secret: GITHUB_USERNAME
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
trigger:
  event:
    - tag
  ref:
    - refs/tags/release-test-*

---
kind: pipeline
name: Release (next)

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: release
    image: node:10
    commands:
      - git checkout  -b master
      - yarn lerna-publish --dist-tag=next --yes

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-next-*

---
kind: pipeline
name: Release (forced)

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test

  - name: release (force)
    image: node:10
    commands:
      - yarn lerna-publish --force-publish --dist-tag=latest

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-latest-*
---
kind: pipeline
name: Canary release

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test
trigger:
  event:
    - push
  branch:
    - canary
---
kind: signature
hmac: 591ab77ba5dc6e6aecd5e3559c1db88ba7d30b87534a4076f5ed132052d45884

...
