---
kind: pipeline
name: Build and Test

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test
    environment:
      SECRET_KEY:
        from_secret: SECRET_KEY
trigger:
  event:
    - push

---
kind: pipeline
name: Publish package
steps:
  - name: Install
    image: node:10
    commands:
      - yarn install
  - name: Publish
    image: node:10
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - git fetch origin master
      - git checkout master
      - git config --global user.email "engineering@bearer.sh"
      - git config --global user.name "Bearer engineering"
      - yarn lerna publish --dist-tag=test --conventional-commits --create-release=github --yes
    environment:
      SECRET_KEY:
        from_secret: SECRET_KEY
      NPM_TOKEN:
        from_secret: NPM_TOKEN
trigger:
  event:
    - tag
  ref:
    - refs/tags/release-test-*

---
kind: pipeline
name: Release (next)

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: release
    image: node:10
    commands:
      - git checkout  -b master
      - yarn lerna-publish --dist-tag=next --yes

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-next-*

---
kind: pipeline
name: Release (forced)

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test

  - name: release (force)
    image: node:10
    commands:
      - yarn lerna-publish --force-publish --dist-tag=latest

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-latest-*
---
kind: pipeline
name: Canary release

steps:
  - name: Install
    image: node:10
    commands:
      - yarn install

  - name: Test
    image: node:10
    commands:
      - yarn test
trigger:
  event:
    - push
  branch:
    - canary
---
kind: signature
hmac: 1ba766d6dc154dc16787287401bebb60e3e29dd4a699f0965fad928f4c5167fe

...
